travis:
  secure:
    BINSTAR_TOKEN: OusAIjQoXyzSFz25YEQJ7CVFW+dbW7H14o/xxg6kU3uNHJjpcB+XTWqknmdGbCPn0WoQPIQcVyvFHbYCswxvSLb4PO/WrepVUrisO8rnrHZUMk9sKv72buUOoNJnDVd3NYZ9Y8/lnVwMzZQtyT+WQEDx81Q+IixSW32BF0ORZOVvDfaQ1yPSpJRJ1VHIiv0YiS9yGliPeaaXK9Co7xzgjJp1EUZsG9fpYvxAbGqo239r03HMrznfKsscEHIToZfRcv4mLUQvZT6R8P7Ciw0NOZlLM32+c5rzTNo1hDyoQYE6Agt2OjKnlhJfl/UQ7y/gPc5t36xMH5ywkEzgOzB9p8lVVSHXvL0Ld3yX0eqPnVUULx+DrFLfqf2qnFI8H2jnjEsxPKJd2jH1NMqhyNkh8uiVG327fpL5sV37g8edwx6lAs1hgVjgx/CpTxUCFasgjQSomNfWPqaqp9s/ZT2rMPIXb82hd4bX3bOAIYssibC3+NcVCM9elewiYdDc8NQhAk47jmN38xwPauzqA3+x6z1t+eEbNIErfPCvLcpqT0DV5/vNXvjio4X750S4qBUue9WpjiGK1s1B8eAH25AAD/EvVueRrqlfUH1PmG0lKKOzwjV6pya8BLGM3LA9BYu85Dl6nS32CW1p3FTE2Ja43igtHdBiyZJJStBLF/BtieQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
